### ISSUE TITLE
Issue with initial install - tool.openai_schema.items() error

### ISSUE THREAD

**Issue by pr0j3c7t0dd** [VRSEN/agency-voice-interface#5]
Hello,

I'm getting the following error with an initial install. I've deleted the default research agency, because that was causing issues, but it also looks like the default tools are causing issues.  I'm running on a mac with m3.

Any help would be appreciated.

Traceback (most recent call last):
  File "[...]/vrsen-agency-voice-interface/.venv/bin/main", line 5, in <module>
    from voice_assistant.main import main
  File "[...]/vrsen-agency-voice-interface/src/voice_assistant/main.py", line 18, in <module>
    from voice_assistant.tools import TOOL_SCHEMAS
  File "[...]/vrsen-agency-voice-interface/src/voice_assistant/tools/__init__.py", line 41, in <module>
    TOOL_SCHEMAS = prepare_tool_schemas()
  File "[...]/vrsen-agency-voice-interface/src/voice_assistant/tools/__init__.py", line 31, in prepare_tool_schemas
    tool_schema = {k: v for k, v in tool.openai_schema.items() if k != "strict"}
                                    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'property' object has no attribute 'items'

Thank you. All the best.

**Comment by pr0j3c7t0dd** [comment]
Here you go... Fresh install, I've never installed the agency-swarm stuff on my machine before.  just ran uv sync as instructed.  thanks.

agency-swarm version: 0.3.1
openai version: 1.51.2

**Comment by bonk1t** [comment]
Hi @pr0j3c7t0dd,

Thank you for sharing the details!

It looks like both agency-swarm and openai are at the recommended versions, so that’s great. However, a few things could still be contributing to the issue:

1. Python Version: Are you running Python 3.12? This version is recommended for compatibility with agency-swarm and openai. If you’re not using 3.12, please try upgrading to it and see if the error persists. If this resolves the issue, I’ll make sure to update the Readme with a note about version requirements.
2. Tool Inheritance: Verify that any custom tools inherit from BaseTool within agency_swarm. This ensures compatibility when preparing tool schemas and may prevent schema-related errors.

If these steps don’t resolve the issue, feel free to share additional details or error logs, and I’d be happy to help further!

**Comment by bonk1t** [comment]
@pr0j3c7t0dd I’m unable to reproduce your error. Could you please try using Python 3.12, as mentioned in the message above? Also, starting fresh by following the instructions in the repo and creating a separate virtual environment may help. Thank you!

**Comment by pr0j3c7t0dd** [comment]
Thanks.  Yes, I installed 3.12 and re-setup the virtual environment and it worked! cheers. For anybody else who wants to do this on a mac... brew install pyenv, pyenv install 3.12, navigate to the agency-voice folder..., pyenv local 3.12, then delete your existing .venv folder, uv venv, uv sync, uv run main - then you should be all set! Cheers.

**Comment by bonk1t** [comment]
Awesome, thank you! Will update the README.md.
